### ISSUE TITLE
xgboost dependency

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#65]
@mschild could you please write what is the right way to install``xgboost`` in our project. @ChulioZ had a problem running the project when using pip install xgboost. can you please comment on this?

**Comment by ChulioZ** [comment]
Here's the error message I get when trying to build a docker image:


  Downloading https://files.pythonhosted.org/packages/83/3a/8570f4e8e19acd3a5a75abc920964182a4b64db2ee0f041fb77b48447c6b/xgboost-0.72.tar.gz (1.1MB)
    Complete output from command python setup.py egg_info:
    + pwd
    + oldpath=/tmp/pip-install-incwk5oc/xgboost
    + cd ./xgboost/
    + grep -q darwin
    + echo
    + LIB_XGBOOST=libxgboost.so
    + make clean
    ./xgboost/build-python.sh: 37: ./xgboost/build-python.sh: make: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-incwk5oc/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-incwk5oc/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-incwk5oc/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-incwk5oc/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-incwk5oc/xgboost/xgboost/./lib/libxgboost.so
    /usr/local/xgboost/libxgboost.so

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-incwk5oc/xgboost/
The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1

**Comment by ChulioZ** [comment]
Yeah, seems to be resolved. Issue was: In the dockerfile I used python 3.6.1-slim and that didn't seem to be working with xgboost. Without the -slim addition it worked, although it took quite a lot of time.
